<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\PortalLocationsController.cs" />
    <Compile Remove="Controllers\PortalVagasController.cs" />
    <Content Remove="Views\PortalVagas\**" />
    <Content Remove="wwwroot\css\portal-candidatos-access.css" />
    <Content Remove="wwwroot\css\portal-vagas.css" />
    <Content Remove="wwwroot\js\views\portal-vagas-access.js" />
    <Content Remove="wwwroot\js\views\portal-vagas-profile-demo.js" />
    <Content Remove="wwwroot\js\views\portal-vagas-profile.js" />
    <Content Remove="wwwroot\js\views\portal-vagas\**" />
    <None Remove="tests\e2e\portal-vagas\**" />
    <None Remove="tests\unit\portal-vagas\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\images\4c9acf59-fb3c-4219-a01e-bb06de70ff5e.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\views\vagas.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
  </ItemGroup>

</Project>
